#include "shell.h"

/**
 * free_array - Frees the array of pointers generated by split_line.
 * @args: The array of pointers to be freed.
 *
 * Return: void.
 */
void free_array(char **args)
{
	if (args != NULL)
		free(args);
}

/**
 * print_error - Prints an error message if a command is not found.
 * @argv0: The name of the shell program (e.g., ./hsh).
 * @cmd: The command that caused the error (e.g., qwerty).
 * @line_count:count
 * Return: void.
 */
void print_error(char *argv0, char *cmd, int line_count)
{
	fprintf(stderr, "%s: %d: %s: not found\n", argv0, line_count, cmd);
	fflush(stderr);
}
